include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    argument_type_not_assignable: true
    invalid_assignment: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_statements: true
    use_super_parameters: true
