name: beamcoda_jobs_partners_flutter
description: BeamCoda Jobs Partners Flutter Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.5
  device_info_plus: ^5.0.5
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  intl: ^0.17.0
  url_launcher: ^6.1.6
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  flutter_datetime_picker: ^1.5.1
  path_provider: ^2.0.11
  dio: ^4.0.6
  permission_handler: ^10.2.0
  open_filex: ^4.3.1
  change_app_package_name: ^1.1.0
  fluttertoast: ^8.1.1
  flutter_sms: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/illustrations/
    - assets/icons/

